# Generated by Django 3.1.6 on 2021-02-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210204_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='back_stock',
            new_name='inventory',
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.SlugField(max_length=40, null=True),
        ),
    ]
