# Generated by Django 3.1.6 on 2021-02-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210205_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='label',
            field=models.SlugField(max_length=40, null=True),
        ),
    ]
