# Generated by Django 3.1.6 on 2021-03-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_parstockrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='par_stock',
        ),
    ]
