# Generated by Django 3.1.6 on 2021-04-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
