# Generated by Django 3.1.6 on 2021-04-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210409_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='label',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='order_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(max_length=25),
        ),
    ]
