# Generated by Django 3.1.6 on 2021-04-12 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20210410_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
